services:
  node-js-server:
    build:
      context: ./server/nodejs/
    ports:
      - 2020:2020
      - 2021:2021
    environment:
      NODE_ENV: production
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_NAME: amalgam
      DB_PASSWORD: secret
      PORT: 3306
    depends_on:
      - mysql
    networks:
      - amalgam-network

  php-apache:
    build:
      context: ./server/php/
      dockerfile: php-apache.dockerfile
    ports:
      - 8888:80
    volumes:
      - ./server/php:/var/www/html
    depends_on:
      - mysql      
    networks:
      - amalgam-network

  mysql:
    image: mariadb:10.6
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: amalgam
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - amalgam-network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php-apache
      - node-js-server
    networks:
      - amalgam-network
      
volumes:
  mysql_data:

networks:
  amalgam-network:
    driver: bridge